branches:
  only:
    - master
language: node_js
node_js:
  - "8"
  - "10"
cache:
  directories:
    - "node_modules"
env:
  global:
    - VUE_APP_NAME=Plus(ThinkSNS+)
    - VUE_APP_KEYWORDS=plus,sns
    - VUE_APP_DESCRIPTION=ThinkSNS+
install:
  - npm install
before_script:
  - npm run build
  - npm run pages:build-404-html
script:
  - npm run lint --no-fix
  - npm run test:unit
