language: node_js
env:
   - BASE_URL=$BASE_URL
node_js:
    - 8
cache:
  directories:
    - "node_modules"
before_install:
    copy .env.example .env
install:
    yarn install
script:
    - yarn lint --fix
    - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: 
    - "dist"
  on:
    branch: master
