language: node_js
node_js:
    - 8
    - 10
cache:
  directories:
    - "node_modules"
install:
    yarn install
script:
    - yarn predeploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: 
    - "dist"
  on:
    branch: master
